name: assets
description: Placeholder for a Dart asset bundle system.
version: 0.0.2
repository: https://github.com/mosuem/assets

environment:
  sdk: ^3.7.0

dependencies:
  http: ^1.1.0
  logging: ^1.3.0
  meta: ^1.16.0
  native_assets_cli: ^0.11.0

dev_dependencies:
  dart_flutter_team_lints: ^3.4.0
  lints: ^5.1.1
  test: ^1.24.0
